"""Add RlltLookup

Revision ID: 053f843f3f26
Revises: 66d4e70c45a4
Create Date: 2026-03-28 05:33:17.673168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '053f843f3f26'
down_revision: Union[str, Sequence[str], None] = '66d4e70c45a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rllt_lookup',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('module', sa.Integer(), nullable=False),
    sa.Column('facet', sa.Integer(), nullable=False),
    sa.Column('phase', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('art', sa.String(), nullable=False),
    sa.Column('scheduled_value_days', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rllt_lookup')
    # ### end Alembic commands ###
