"""add location_id to user and assessment

Revision ID: 112233445566
Revises: 57ac37080c0d
Create Date: 2026-04-09 10:50:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '112233445566'
down_revision: Union[str, Sequence[str], None] = '57ac37080c0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location_id', sa.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'users', 'locations', ['location_id'], ['id'])
    
    op.add_column('assessments', sa.Column('location_id', sa.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'assessments', 'locations', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assessments', type_='foreignkey')
    op.drop_column('assessments', 'location_id')
    
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'location_id')
    # ### end Alembic commands ###
