"""Add Assignment Targets

Revision ID: 11a8835deb7f
Revises: af74edb98369
Create Date: 2026-05-01 01:48:05.107430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11a8835deb7f'
down_revision: Union[str, Sequence[str], None] = 'af74edb98369'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classroom_assignments', sa.Column('group_id', sa.UUID(), nullable=True))
    op.add_column('classroom_assignments', sa.Column('student_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'classroom_assignments', 'users', ['student_id'], ['id'])
    op.create_foreign_key(None, 'classroom_assignments', 'student_groups', ['group_id'], ['id'])
    op.add_column('classroom_submissions', sa.Column('file_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classroom_submissions', 'file_url')
    op.drop_constraint(None, 'classroom_assignments', type_='foreignkey')
    op.drop_constraint(None, 'classroom_assignments', type_='foreignkey')
    op.drop_column('classroom_assignments', 'student_id')
    op.drop_column('classroom_assignments', 'group_id')
    # ### end Alembic commands ###
