"""add_assessment_marks

Revision ID: 30f8dc27cfbc
Revises: abe8a4f2812a
Create Date: 2026-04-10 08:53:00.605018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30f8dc27cfbc'
down_revision: Union[str, Sequence[str], None] = 'abe8a4f2812a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('assessment_marks', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'assessment_marks')
    # ### end Alembic commands ###
