"""Add audio_language to contents

Revision ID: 3b799ed991f1
Revises: 37fb8678e28e
Create Date: 2026-04-13 12:57:20.831835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b799ed991f1'
down_revision: Union[str, Sequence[str], None] = '37fb8678e28e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('audio_language', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contents', 'audio_language')
    # ### end Alembic commands ###
