"""Add category and stage to User

Revision ID: 56ecf16b7535
Revises: 112233445566
Create Date: 2026-04-10 06:34:42.116464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56ecf16b7535'
down_revision: Union[str, Sequence[str], None] = '112233445566'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('category', sa.String(), nullable=True))
    op.add_column('users', sa.Column('stage', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'stage')
    op.drop_column('users', 'category')
    # ### end Alembic commands ###
