"""Add VCardMapping

Revision ID: 57ac37080c0d
Revises: 894725f70063
Create Date: 2026-04-03 13:02:26.722561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57ac37080c0d'
down_revision: Union[str, Sequence[str], None] = '894725f70063'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vcard_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('module', sa.Integer(), nullable=False),
    sa.Column('facet', sa.Integer(), nullable=False),
    sa.Column('phase', sa.Integer(), nullable=False),
    sa.Column('banner_text', sa.String(), nullable=True),
    sa.Column('t_label', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('state_payload', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module', 'facet', 'phase', name='uq_vcard_mapping_mfp')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vcard_mappings')
    # ### end Alembic commands ###
