"""Make location_id nullable in resources

Revision ID: 5d9b75eca7aa
Revises: dfbf103dd258
Create Date: 2026-05-01 00:54:42.221020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d9b75eca7aa'
down_revision: Union[str, Sequence[str], None] = 'dfbf103dd258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classroom_resources', 'location_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classroom_resources', 'location_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
