"""Add SevenTNTDayCycleChartMapping

Revision ID: 6990a9f5807a
Revises: 27351810be11
Create Date: 2026-04-18 12:47:30.792886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6990a9f5807a'
down_revision: Union[str, Sequence[str], None] = '27351810be11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seven_tnt_day_cycle_chart_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('module', sa.Integer(), nullable=False),
    sa.Column('facet', sa.Integer(), nullable=False),
    sa.Column('phase', sa.Integer(), nullable=False),
    sa.Column('banner_text', sa.String(), nullable=True),
    sa.Column('t_label', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('state_payload', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module', 'facet', 'phase', name='uq_seven_tnt_day_cycle_chart_mapping_mfp')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seven_tnt_day_cycle_chart_mappings')
    # ### end Alembic commands ###
