"""Add pdf_url to contents

Revision ID: 980d8c457d12
Revises: 3b799ed991f1
Create Date: 2026-04-13 17:29:33.671253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '980d8c457d12'
down_revision: Union[str, Sequence[str], None] = '3b799ed991f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('pdf_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contents', 'pdf_url')
    # ### end Alembic commands ###
