"""Add assessment_status to user

Revision ID: abe8a4f2812a
Revises: 56ecf16b7535
Create Date: 2026-04-10 04:29:12.719576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abe8a4f2812a'
down_revision: Union[str, Sequence[str], None] = '56ecf16b7535'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('assessment_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'assessment_status')
    # ### end Alembic commands ###
