"""Add words to chapters

Revision ID: cd484d0ca7a6
Revises: f50791960d58
Create Date: 2026-05-19 02:26:00.685873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd484d0ca7a6'
down_revision: Union[str, Sequence[str], None] = 'f50791960d58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('english_words', sa.Integer(), nullable=True))
    op.add_column('chapters', sa.Column('hebrew_words', sa.Integer(), nullable=True))
    op.add_column('chapters', sa.Column('greek_words', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapters', 'greek_words')
    op.drop_column('chapters', 'hebrew_words')
    op.drop_column('chapters', 'english_words')
    # ### end Alembic commands ###
