"""Add ClassroomResource table

Revision ID: dfbf103dd258
Revises: e298a7388c7d
Create Date: 2026-04-30 17:25:27.016170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfbf103dd258'
down_revision: Union[str, Sequence[str], None] = 'e298a7388c7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('classroom_resources',
    # sa.Column('id', sa.UUID(), nullable=False),
    # sa.Column('location_id', sa.UUID(), nullable=False),
    # sa.Column('title', sa.String(), nullable=False),
    # sa.Column('resource_type', sa.String(), nullable=False),
    # sa.Column('url', sa.String(), nullable=False),
    # sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    # sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    # sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('classroom_resources')
    # ### end Alembic commands ###
