"""add_notes

Revision ID: e298a7388c7d
Revises: 6990a9f5807a
Create Date: 2026-04-18 19:14:47.869340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e298a7388c7d'
down_revision: Union[str, Sequence[str], None] = '6990a9f5807a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word_documents', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('word_documents', 'notes')
    # ### end Alembic commands ###
