"""Add choices to ClassroomQnA

Revision ID: f30791960d56
Revises: 11a8835deb7f
Create Date: 2026-05-01 06:42:12.291577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f30791960d56'
down_revision: Union[str, Sequence[str], None] = '11a8835deb7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classroom_qna', sa.Column('seven_tnt', sa.String(), nullable=True))
    op.add_column('classroom_qna', sa.Column('category', sa.String(), nullable=True))
    op.add_column('classroom_qna', sa.Column('stage', sa.String(), nullable=True))
    op.add_column('classroom_qna', sa.Column('choices', sa.JSON(), nullable=True))
    op.alter_column('classroom_qna', 'answer_text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classroom_qna', 'answer_text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('classroom_qna', 'choices')
    op.drop_column('classroom_qna', 'stage')
    op.drop_column('classroom_qna', 'category')
    op.drop_column('classroom_qna', 'seven_tnt')
    # ### end Alembic commands ###
